apiVersion: v1
kind: Service
metadata:
#  name: {{ include "block-buster-helm-app.fullname" . }}
  name: demo5-helm-release
  labels:
    app: {{ .Values.labels.app.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
        app: {{ .Values.labels.app.name }}
        version: {{ .Values.labels.app.version }}
        env: {{ .Values.labels.app.env }}
